"""Constraint data models for the unit inference engine.

Each constraint relates the units of variables through dimensional rules:
    - EqualityConstraint:  unit(a) == unit(b)
    - ProductConstraint:   unit(result) == unit(a) + unit(b)   [dimension addition]
    - QuotientConstraint:  unit(result) == unit(a) - unit(b)   [dimension subtraction]
    - PowerConstraint:     unit(result) == n * unit(base)      [dimension scaling]
    - KnownUnitConstraint: unit(var) == specific_unit_vector   [from annotation]

Every constraint carries source location for error reporting.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction

from unit_checker.core.unit_algebra import UnitVector
from unit_checker.parsers.common.ir import SourceLocation


@dataclass
class Constraint:
    """Base class for all constraints."""
    location: SourceLocation
    description: str  # Human-readable description of why this constraint exists

    def involved_variables(self) -> list[str]:
        """Return qualified names of all variables involved in this constraint."""
        raise NotImplementedError


@dataclass
class EqualityConstraint(Constraint):
    """unit(var_a) == unit(var_b).

    Generated by: assignment (c = a), addition/subtraction operands,
    function argument passing, comparison operators.
    """
    var_a: str  # Qualified variable name
    var_b: str  # Qualified variable name

    def involved_variables(self) -> list[str]:
        return [self.var_a, self.var_b]


@dataclass
class ProductConstraint(Constraint):
    """unit(result) == unit(operand_a) + unit(operand_b).

    Generated by: multiplication (c = a * b).
    Dimension vectors ADD for products.
    """
    result: str    # Qualified variable name for result
    operand_a: str  # Qualified variable name for left operand
    operand_b: str  # Qualified variable name for right operand

    def involved_variables(self) -> list[str]:
        return [self.result, self.operand_a, self.operand_b]


@dataclass
class QuotientConstraint(Constraint):
    """unit(result) == unit(numerator) - unit(denominator).

    Generated by: division (c = a / b).
    Dimension vectors SUBTRACT for quotients.
    """
    result: str      # Qualified variable name for result
    numerator: str   # Qualified variable name for numerator
    denominator: str  # Qualified variable name for denominator

    def involved_variables(self) -> list[str]:
        return [self.result, self.numerator, self.denominator]


@dataclass
class PowerConstraint(Constraint):
    """unit(result) == exponent * unit(base).

    Generated by: exponentiation (c = a ** n).
    Dimension vector is SCALED by the exponent.
    """
    result: str       # Qualified variable name for result
    base: str         # Qualified variable name for base
    exponent: Fraction  # The power exponent (must be a constant)

    def involved_variables(self) -> list[str]:
        return [self.result, self.base]


@dataclass
class KnownUnitConstraint(Constraint):
    """unit(var) == specific_unit_vector.

    Generated by: user annotations (comments, type hints, decorators).
    """
    variable: str       # Qualified variable name
    unit: UnitVector    # The known unit

    def involved_variables(self) -> list[str]:
        return [self.variable]


@dataclass
class AdditionConstraint(Constraint):
    """Composite constraint for addition/subtraction: c = a + b.

    This encodes:
        unit(result) == unit(left)
        unit(left) == unit(right)

    All three must have the same dimensions.
    """
    result: str
    left: str
    right: str

    def involved_variables(self) -> list[str]:
        return [self.result, self.left, self.right]
